version: "3.8"
services:
  # From `Dockerfile` in current directory
  bigmuseum:
    container_name: bigmuseum
    hostname: bigmuseum
    # Pass environment from .env
    env_file:
      - .env
    build:
      context: .
    # Host port 8000, container port 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Ensure `/app/node_modules` is always empty in the container, so Node ignores it
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=crazy-squint-precook-saline
      - MONGO_INITDB_DATABASE=bigmuseum
  # mongodb:
  #   container_name: mongodb
  #   hostname: mongodb
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules  # Ensure `/app/node_modules` is always empty in the container, so Node ignores it
